#!/bin/bash

if [[ "${PACKAGE_PATH}" == "" ]]; then
    PROCESS_PATH=`ps -p $PPID -o comm=`
    PROCESS_NAME=$(basename ${PROCESS_PATH})
    case "${PROCESS_NAME}" in
        Installer)
            PACKAGE_PATH=`sed -n -e "s/^.*Installer\[${PPID}\]: Opened from: //p" /var/log/install.log | tail -n1`
            ;;
        installer)
            PACKAGE_PATH=`lsof -Fn -p $PPID | grep "n.*[.]pkg" | tail -n1 | cut -b 2-`
            ;;
    esac

    #echo `date` "${PROCESS_NAME}($PPID)" "PACKAGE_PATH: ${PACKAGE_PATH}" >> ~/Desktop/PACKAGE_PATH.TXT
fi

exit 0

