#!/bin/bash

if [[ "${PACKAGE_PATH}" == "" ]]; then
    PROCESS_PATH=`ps -p $PPID -o comm=`
    if [[ "${PROCESS_PATH}" == */Installer.app/Contents/MacOS/Installer ]];
    then
        PACKAGE_PATH=`sed -n -e "s/^.*Installer\[${PPID}\]: Opened from: //p" /var/log/install.log | tail -n1`
    else
        PACKAGE_PATH=`lsof -Fn -p $PPID | grep "n.*[.]pkg" | tail -n1 | cut -b 2-`
    fi

    #echo `date` "${PROCESS_NAME}($PPID)" "PACKAGE_PATH: ${PACKAGE_PATH}" >> ~/Desktop/PACKAGE_PATH.TXT
fi

exit 0

